// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsI0sXvSIFLe8vnAcDWwaWpHRYtRqzIQA',
    appId: '1:67982497309:web:e07f8e4b79747694f218f4',
    messagingSenderId: '67982497309',
    projectId: 'fashion-c2ea3',
    authDomain: 'fashion-c2ea3.firebaseapp.com',
    storageBucket: 'fashion-c2ea3.appspot.com',
    measurementId: 'G-PJYP26J783',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLS6sD1tBwCkxWQ7t1I_qUdXTacX_FkP0',
    appId: '1:67982497309:android:855a3dd1c22b659cf218f4',
    messagingSenderId: '67982497309',
    projectId: 'fashion-c2ea3',
    storageBucket: 'fashion-c2ea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiyfSvLlalbs4vMfvBHn3UFnDoyPj5big',
    appId: '1:67982497309:ios:42f46328a6c0d170f218f4',
    messagingSenderId: '67982497309',
    projectId: 'fashion-c2ea3',
    storageBucket: 'fashion-c2ea3.appspot.com',
    iosBundleId: 'com.example.fashion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiyfSvLlalbs4vMfvBHn3UFnDoyPj5big',
    appId: '1:67982497309:ios:42f46328a6c0d170f218f4',
    messagingSenderId: '67982497309',
    projectId: 'fashion-c2ea3',
    storageBucket: 'fashion-c2ea3.appspot.com',
    iosBundleId: 'com.example.fashion2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsI0sXvSIFLe8vnAcDWwaWpHRYtRqzIQA',
    appId: '1:67982497309:web:b1738f92ae2600edf218f4',
    messagingSenderId: '67982497309',
    projectId: 'fashion-c2ea3',
    authDomain: 'fashion-c2ea3.firebaseapp.com',
    storageBucket: 'fashion-c2ea3.appspot.com',
    measurementId: 'G-0VKS2DX8F4',
  );
}
